language: ruby

rvm:
  - 2.5.1

before_install:
  - gem install bundler -v '2.1.1'

before_script:
- psql -c ‘CREATE DATABASE drinkee-frontend_test;’ -U postgres

dist: trusty

os: osx

services:
  - postgresql
